version: "2.26.1"
services:
  microservicios:
    container_name: microservicios
    image: jhonfwh2024/microservicios-funcionarios:latest
    ports: 
      - "5173:5173"
    networks:
      - proyectos-app

  mayordemanda:
    container_name: mayordemanda
    image: jhonfwh2024/appmonolito:latest
    depends_on:
      - microservicios
    environment:
      API_URL: http://microservicios:5173
    ports:
      - "5172:5172"
    networks:
      - proyectos-app

networks:
  proyectos-app:
